version: '3.3'
services:
  bombsquad-server:
    image: mohammadmazraeh/bombsquad-server:latest
    network_mode: host
    container_name: bombsquad-server
    volumes:
      - ./config.py:/BombSquad_Server/config.py:rw
    entrypoint: sleep infinity
    #entrypoint: python ./bombsquad_server
