version: '3.3'
services:
  bombsquad-server:
    build: .
    network_mode: host
    container_name: bombsquad-server
    entrypoint: ./BombSquad_Server/bombsquad_server
    volumes:
      - ./config.py:/BombSquad_Server/config.py
